<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.vipin.lottery</groupId>
    <artifactId>lottery</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <lombok.version>1.18.22</lombok.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
    <packaging>pom</packaging>

    <modules>
        <module>as-number</module>
        <module>all-combinations</module>
        <module>groupingrange</module>
        <module>maxmindiffoccurence</module>
        <module>occurencestudy</module>
        <module>sortfile</module>
        <module>sumapplication</module>
        <module>totsincecombined</module>
        <module>web-element-extract</module>
        <module>db-connection-lottery</module>
        <module>range-occurence-study</module>
        <module>level-one-intelligence</module>
        <module>deviation-mean-sum-eachlot</module>
        <module>groupingrangecomparewithsuperset</module>
        <module>production</module>
        <module>powerball-sync</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>


</project>
